platform :ios, '8.0'
#use_frameworks!
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitee.com/dvlproad/dvlproadSpecs'

inhibit_all_warnings!

target 'CJStandardProjectDemo' do
    pod 'Masonry'
    pod 'MBProgressHUD'
    pod 'SVProgressHUD'
    pod 'MJRefresh'
    pod 'CocoaAsyncSocket'
    
    pod 'ReactiveObjC', '~> 3.1.0'
    
    pod 'CJBaseUIKit', :subspecs => ['UIColor', 'UIButton', 'UITextField', 'CJToast', 'CJAlert']
    pod 'CJBaseUtil', :subspecs => ['CJLog', 'CJDevice']
    pod 'CJFoundation', :subspecs => ['NSString']
    pod 'CJNetwork', :subspecs => ['AFNetworkingBaseComponent']
    pod 'OpenUDID'
    pod 'CJBaseUtil/CJAppLastUtil' # 账号密码处理等，其中包含钥匙串存取数据(SAMkeychain)
    pod 'CJFile', :subspecs => ['CJFileModel', 'CJFileManager', 'CJFMDBFileManager']

    # 模块化需要依赖的库
    pod 'CTMediator'
    
    
    pod 'CJDemoModuleMain/CJDemoModuleMain_Category'
end

target 'CJStandardProjectDemoTests' do
   
end
