platform :ios, '8.0'
#use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitee.com/dvlproad/dvlproadSpecs'

inhibit_all_warnings!

target 'CJStandardProjectDemo' do
    pod 'Masonry'
    pod 'MBProgressHUD'
    pod 'SVProgressHUD'
    pod 'AFNetworking'
    pod 'CocoaAsyncSocket'
    
    pod 'ReactiveObjC', '~> 3.1.0'
    
    pod 'CJBaseUIKit', :subspecs => ['UIButton', 'UITextField', 'CJToast', 'CJAlert']
    pod 'CJBaseUtil', :subspecs => ['CJLog']
    
    pod 'CJDemoModel', :subspecs => ['CJDemoUser']
end

target 'CJStandardProjectDemoTests' do
   
end
