platform :ios, '8.0'
#use_frameworks!

target 'CJFoundationDemo' do
    pod 'CJBaseUIKit/CJTextField', '~> 0.0.10'
    pod 'CJBaseUIKit/UIColor+CJCategory', '~> 0.0.10'
    pod 'YYText', '~> 1.0.7'
    
	pod 'CJPicker', '~> 1.2.0'
	pod 'CJPopupAction', '~> 1.4.2'
end

target 'CJFoundationDemoTests' do
    
end
