platform :ios, '8.0'
#use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitee.com/dvlproad/dvlproadSpecs'

inhibit_all_warnings!

target 'CJAutoPackageDemo' do
    
end

target 'CJAutoPackageDemoTests' do
   
end
